core/urls.py
from django.contrib import admin
from django.urls import path, include

from core import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("apps.authentication.urls")),

    # ADD NEW Routes HERE

    path("", include("apps.home.urls"))
]

# To display images
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/home/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""
import os

from django.core.files.storage import FileSystemStorage
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models import IntegerField, DecimalField

from core import settings


class Channel(models.Model):
    source = models.CharField(max_length=150)
    camera_name = models.CharField(max_length=150)
    camera_id = models.CharField(max_length=150, blank=True, null=True)
    apple_hls = models.CharField(max_length=150, blank=True, null=True)
    jpeg_url = models.CharField(max_length=150, blank=True, null=True)
    latitude = models.CharField(max_length=150, blank=True, null=True)
    longitude = models.CharField(max_length=150, blank=True, null=True)

    def __str__(self):
        return "{}".format(self.camera_name)


class ChannelGroup(models.Model):
    title = models.CharField(max_length=150, default="Default Channel Group")

    slot1 = models.ForeignKey(Channel, related_name='slot1', on_delete=models.CASCADE, blank=True, null=True)
    slot2 = models.ForeignKey(Channel, related_name='slot2', on_delete=models.CASCADE, blank=True, null=True)
    slot3 = models.ForeignKey(Channel, related_name='slot3', on_delete=models.CASCADE, blank=True, null=True)
    slot4 = models.ForeignKey(Channel, related_name='slot4', on_delete=models.CASCADE, blank=True, null=True)
    slot5 = models.ForeignKey(Channel, related_name='slot5', on_delete=models.CASCADE, blank=True, null=True)
    slot6 = models.ForeignKey(Channel, related_name='slot6', on_delete=models.CASCADE, blank=True, null=True)

    active = models.BooleanField(default=False)

    def __str__(self):
        return "[SELECTED] {}".format(self.title) if self.active else "{}".format(self.title)


class AIModel(models.Model):
    title = models.CharField(max_length=150)

    model_bin = models.FileField(storage=FileSystemStorage(location=settings.MEDIA_ROOT), upload_to='models/')

    model_xml = models.FileField(storage=FileSystemStorage(location=settings.MEDIA_ROOT), upload_to='models/')

    floating_point_precision = models.CharField(
        max_length=9,
        default=("FP16", "FP16"),
        choices=(
            ("FP16", "FP16"),
            ("FP16-INT8", "FP16-INT8"),
            ("FP32", "FP32"),
            ("FP64", "FP64"),
        ), blank=False)

    device = models.CharField(
        max_length=9,
        default=("CPU", "CPU"), choices=(
            ("CPU", "CPU"),
            ("GPU", "GPU"),
            ("HDDL", "HDDL"),
            ("MYRIAD", "MYRIAD"),
        ), blank=False)

    person_label = IntegerField(default=1, validators=[MaxValueValidator(5), MinValueValidator(0)], blank=False)
    vehicle_label = IntegerField(default=2, validators=[MaxValueValidator(5), MinValueValidator(0)], blank=False)
    bike_label = IntegerField(default=3, validators=[MaxValueValidator(5), MinValueValidator(0)], blank=False)

    threshold = DecimalField(default=0.5, max_digits=2, decimal_places=2, validators=[MaxValueValidator(1),
                                                                                      MinValueValidator(0)])

    output_size = IntegerField(default=7, validators=[MaxValueValidator(7), MinValueValidator(7)], blank=False)

    def __str__(self):
        return "{}".format(self.title)


class ConfigChannel(models.Model):
    channel = models.ForeignKey(Channel, db_column='channel', on_delete=models.CASCADE)
    model = models.ForeignKey(AIModel, db_column='model', on_delete=models.CASCADE)

    vehicle_object_color = models.CharField(default="#5eb5ef", max_length=150, blank=True, null=True)
    vehicle_threshold = DecimalField(default=0.5, max_digits=1, decimal_places=1, validators=[MaxValueValidator(1),
                                                                                              MinValueValidator(0)])

    bike_object_color = models.CharField(default="#ffd878", max_length=150, blank=True, null=True)
    bike_threshold = DecimalField(default=0.5, max_digits=1, decimal_places=1, validators=[MaxValueValidator(1),
                                                                                           MinValueValidator(0)])

    person_object_color = models.CharField(default="#ff829d", max_length=150, blank=True, null=True)
    person_threshold = DecimalField(default=0.5, max_digits=1, decimal_places=1, validators=[MaxValueValidator(1),
                                                                                             MinValueValidator(0)])

    def __str__(self):
        return "{}".format(self.channel.camera_name)


class BaseConfig(models.Model):
    model = models.ForeignKey(AIModel, db_column='model', on_delete=models.CASCADE)

    vehicle_object_color = models.CharField(default="#5eb5ef", max_length=150, blank=True, null=True)
    vehicle_threshold = DecimalField(default=0.5, max_digits=1, decimal_places=1, validators=[MaxValueValidator(1),
                                                                                              MinValueValidator(0)])

    bike_object_color = models.CharField(default="#ffd878", max_length=150, blank=True, null=True)
    bike_threshold = DecimalField(default=0.5, max_digits=1, decimal_places=1, validators=[MaxValueValidator(1),
                                                                                           MinValueValidator(0)])

    person_object_color = models.CharField(default="#ff829d", max_length=150, blank=True, null=True)
    person_threshold = DecimalField(default=0.5, max_digits=1, decimal_places=1, validators=[MaxValueValidator(1),
                                                                                             MinValueValidator(0)])

    selected = models.BooleanField(default=False)

    def __str__(self):
        return "[SELECTED] Config of Model- {}".format(
            self.model.title) if self.selected else "Config of Model- {}".format(
            self.model.title)


class CollisionConfig(models.Model):
    collision_event_text = models.CharField(default="Collided", max_length=150, blank=True, null=True)
    collision_box_color = models.CharField(default="#FF2D00", max_length=150, blank=True, null=True)

    near_miss_event_text = models.CharField(default="Near Missed!!", max_length=150, blank=True, null=True)
    near_miss_box_color = models.CharField(default="#FFAD00", max_length=150, blank=True, null=True)

    collision_definition = models.CharField(
        max_length=250,
        default=("1", "If two or more objects intersect 25% each other"), choices=(
            ("0", "If two or more objects bodies touches"),
            ("1", "If two or more objects intersect 25% each other"),
            ("2", "If two or more objects intersect 50% each other"),
            ("3", "If two or more objects intersect 75% each other")
        ), blank=False)

    near_miss_definition = models.CharField(
        max_length=250,
        default=("0", "If two or more objects intersection is less than 25%"), choices=(
            ("0", "If two or more objects intersection is less than 25%"),
            ("1", "If two or more objects intersection is less than 50%")
        ), blank=False)

    selected = models.BooleanField(default=False)

    def __str__(self):
        return "[SELECTED] Config of Collision- {} Near Miss- {}".format(
            self.collision_event_text, self.near_miss_event_text) \
            if self.selected else "Config of Collision- {}".format(
            self.collision_event_text, self.near_miss_event_text)


class Process(models.Model):
    channel = models.ForeignKey(Channel, db_column='channel', on_delete=models.CASCADE)

    collisions = IntegerField(default=0, blank=True)
    near_misses = IntegerField(default=0, blank=True)
    vehicles = IntegerField(default=0, blank=True)
    bikes = IntegerField(default=0, blank=True)
    persons = IntegerField(default=0, blank=True)

    current = models.BooleanField(default=False)

    def __str__(self):
        return "{}".format(self.channel.camera_name)


class GraphConfig(models.Model):
    update_every = models.CharField(
        max_length=250,
        default=("1", "1 Seconds"), choices=(
            ("1", "1 Seconds"),
            ("5", "5 Seconds"),
            ("10", "10 Seconds"),
            ("15", "15 Seconds"),
            ("30", "30 Seconds"),
            ("60", "60 Seconds")
        ), blank=False)

    vehicle_flow_label = models.CharField(default="Vehicles", max_length=150, blank=True, null=True)
    vehicle_flow_color = models.CharField(default="#5eb5ef", max_length=150, blank=True, null=True)
    bike_flow_label = models.CharField(default="Bike", max_length=150, blank=True, null=True)
    bike_flow_color = models.CharField(default="#ffd878", max_length=150, blank=True, null=True)
    person_flow_label = models.CharField(default="Pedestrians", max_length=150, blank=True, null=True)
    person_flow_color = models.CharField(default="#ff829d", max_length=150, blank=True, null=True)

    vehicle_analysis_label = models.CharField(default="Vehicles", max_length=150, blank=True, null=True)
    vehicle_analysis_color = models.CharField(default="#5eb5ef", max_length=150, blank=True, null=True)
    bike_analysis_label = models.CharField(default="Bike", max_length=150, blank=True, null=True)
    bike_analysis_color = models.CharField(default="#ffd878", max_length=150, blank=True, null=True)
    person_analysis_label = models.CharField(default="Pedestrians", max_length=150, blank=True, null=True)
    person_analysis_color = models.CharField(default="#ff829d", max_length=150, blank=True, null=True)

    collision_label = models.CharField(default="Collisions", max_length=150, blank=True, null=True)
    collision_color = models.CharField(default="#FF2D00", max_length=150, blank=True, null=True)
    nearmiss_label = models.CharField(default="Near Miss", max_length=150, blank=True, null=True)

apps/templates/modals/channel_config.html
<div class="modal fade" id="channelConfigModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Channel Configuration</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="" method="POST" class="pop-up-form__form" id="channel_config_form"
                      enctype="multipart/form-data">
                    {% csrf_token %}

                    <label for="id_model" class="col-form-label">Detection Model</label>
                    <select class="form-select mb-3" name="model" id="id_model">
                        {% for model in models %}
                        <option value="{{ model.id }}"
                                {% if model_config.title == model.title %}selected="selected" {% endif %}
                        >{{ model.title }}
                        </option>
                        {% endfor %}
                    </select>

                    <!-- Vehicle -->
                    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center">
                        <div class="mb-3 col-6" style="padding-right:5px">
                            <label for="id_vehicle" class="col-form-label">Vehicle
                                threshold</label>
                            <input name="vehicleTh" type="number" class="form-control" id="id_vehicle" autocomplete="off"
                                   value="{{ model_config.vehicle_threshold }}" min="0.00"
                                   max="1.00" step=".01"/>
                        </div>

                        <div class="mb-3 col-6"
                             style="padding-left:5px">
                            <label for="vehicleColor" class="col-form-label">Vehicle Object Color</label>
                            <input name="vehicleColor" type="color" class="form-control form-control-color w-100" id="vehicleColor"
                                   value="{{ model_config.vehicle_object_color }}"
                                   title="Choose a color">
                        </div>
                    </div>

                    <!-- Bike -->
                    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center">
                        <div class="mb-3 col-6"
                             style="padding-right:5px">
                            <label for="id_bike" class="col-form-label">Bike
                                threshold</label>

                            <input name="bikeTh" type="number" class="form-control" id="id_bike" autocomplete="off"
                                   value="{{ model_config.bike_threshold }}" min="0.00"
                                   max="1.00" step=".01"/>
                        </div>

                        <div class="mb-3 col-6"
                             style="padding-left:5px">
                            <label for="bikeColor" class="col-form-label">Bike Object Color</label>
                            <input name="bikeColor" type="color" class="form-control form-control-color w-100" id="bikeColor"
                                   value="{{ model_config.bike_object_color }}"
                                   title="Choose a color">
                        </div>
                    </div>

                    <!-- Person -->
                    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center">
                        <div class="mb-3 col-6"
                             style="padding-right:5px">
                            <label for="id_person" class="col-form-label">Person
                                threshold</label>

                            <input name="personTh" type="number" class="form-control" id="id_person" autocomplete="off"
                                   value="{{ model_config.person_threshold }}" min="0.00"
                                   max="1.00" step=".01"/>
                        </div>

                        <div class="mb-3 col-6"
                             style="padding-left:5px">
                            <label for="personColor" class="col-form-label">Person Object Color</label>
                            <input name="personColor" type="color" class="form-control form-control-color w-100" id="personColor"
                                   value="{{ model_config.person_object_color }}"
                                   title="Choose a color">
                        </div>
                    </div>


                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-primary" form="channel_config_form">Update</button>
            </div>
        </div>
    </div>
</div>
<script>

    $(document).ready(function () {

    });

</script>

apps/templates/modals/channel_picker.html
<div class="modal fade" id="channelPickerModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Select Channel</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">

                <table class="table table-striped display" style="width:100%" id="channelTable">
                    <thead>
                    <tr>
                        <th class="border-gray-200" >Thumbnail</th>
                        <th class="border-gray-200" >Channel Id</th>
                        <th class="border-gray-200">Title</th>
                        <th class="border-gray-200">Channel type</th>
                        <th class="border-gray-200" style="text-align: right">Action</th>
                    </tr>
                    </thead>
                </table>

                <input type="hidden" id="slotName" name="slotName" value="">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>

    <script>

    $(document).ready(function () {

        $('#channelTable').dataTable({
            responsive: true,
            serverSide: true,
            sAjaxSource: "/channels-list/",
            columns: [
                {
                    name: "jpeg_url",
                    data: 5,
                    render: function (data) {
                        if( data != null) {
                            return `<img class="bg-light rounded" style="width:80px; height:60px; object-fit: cover;"
                                     src="${data}"/>`;
                        }else {
                            return `<img class="bg-light bg-gradient rounded" style="width:80px; height:60px; object-fit: contain;"
                                     src="https://img.icons8.com/fluency/240/null/link.png"/>`;
                        }
                    }
                },
                {name: "id", data: 0},
                {name: "camera_name", data: 2},
                {name: "source", data: 1},
                {
                    name: "source",
                    data: 1,
                    className: 'dt-right',
                    render: function (data, type, row ) {
                        return `<span class="text-right">
                                <button id="${row[0]}" class="btn btn-primary remove-underline mx-2 my-2 action-button">
                                    Select
                                </button>
                            </span>`;
                    },
                    createdCell: function (td, cellData, rowData, row, col) {
                        $(td).find('button').on('click', function () {

                            var url = $(location).attr('href');
                            var token = "{{csrf_token}}";
                            var slotName = $("#slotName").val();

                            $.ajax({
                                url:  url,
                                type: "POST",
                                data: {
                                    "csrfmiddlewaretoken": token,
                                    "channel_id": rowData[0],
                                    "slot_name": slotName
                                },
                                success: (response) => {
                                    window.location.href=url;
                                },
                                error: (response) => {

                                }
                            });

                        });
                    }
                }
            ],
        });

    });

</script>


</div>

apps/templates/modals/create_channel.html
<div class="modal fade" id="createChannelModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">New channel</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="" method="POST" class="pop-up-form__form" id="create_channel_form"
                      enctype="multipart/form-data">
                    {% csrf_token %}

                    <label for="id_source" class="col-form-label">Channel Source</label>
                    <select class="form-select mb-3" name="source" id="id_source">
                        <option value="Elko" selected>Elko</option>
                        <option value="Reno">Reno</option>
                        <option value="Las Vegas">Las Vegas</option>
                        <option value="Link">Link</option>
                        <option value="Video">Video</option>
                        <option value="Image">Image</option>
                    </select>

                    <div class="mb-3" id="input-camera-name">
                        <label id="label_camera_name" for="id_camera_name" class="col-form-label">Camera Name</label>
                        <input type="text" class="form-control" name="title" maxlength="150" id="id_camera_name"
                               required>
                    </div>

                    <div class="mb-3 d-none" id="input-camera-id">
                        <label for="id_camera_id" class="col-form-label">Camera ID</label>
                        <input type="text" class="form-control" name="id" maxlength="150" id="id_camera_id">
                    </div>

                    <div class="mb-3" id="input-apple-hls">
                        <label id="label_apple_hls" for="id_apple_hls" class="col-form-label">Apple HLS</label>
                        <input type="text" class="form-control" name="apple_hls" maxlength="150" id="id_apple_hls" required>
                    </div>

                    <div class="mb-3" id="input-jpeg-url">
                        <label id="label_jpeg_url" for="id_jpeg_url" class="col-form-label">JPEG URL</label>
                        <input type="text" class="form-control" name="jpeg_url" maxlength="150" id="id_jpeg_url" required>
                    </div>

                    <div class="mb-3" id="input-latitude">
                        <label for="id_latitude" class="col-form-label">Latitude</label>
                        <input type="text" class="form-control" name="latitude" maxlength="150" id="id_latitude">
                    </div>

                    <div class="mb-3" id="input-longitude">
                        <label for="id_longitude" class="col-form-label">Longitude</label>
                        <input type="text" class="form-control" name="longitude" maxlength="150" id="id_longitude">
                    </div>

                    <div class="mb-3 d-none" id="input-file">
                        <label id="label_file" for="id_file" class="form-label">Video File</label>
                        <input type="file" class="form-control" name="file" accept="video/*" id="id_file">
                    </div>

                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" form="create_channel_form">Add channel</button>
            </div>
        </div>
    </div>
</div>
<script>

    $(document).ready(function () {

        var source = $("select[name='source']");
        var cameraName = $('#input-camera-name');
        var appleHls = $('#input-apple-hls');
        var jpegURL = $('#input-jpeg-url');
        var latitude = $('#input-latitude');
        var longitude = $('#input-longitude');
        var file = $('#input-file');

        source.change(function(){
            var sourceElement = document.getElementById('id_source')

            if(sourceElement[0].selected || sourceElement[1].selected || sourceElement[2].selected) {

                appleHls.removeClass('d-none')
                jpegURL.removeClass('d-none')
                latitude.removeClass('d-none')
                longitude.removeClass('d-none')
                file.addClass('d-none')

                $('#id_apple_hls').attr('required', true);
                $('#id_jpeg_url').attr('required', true);
                $('#id_file').attr('required', false);

                $("#label_camera_name").text("Camera Name");
                $("#label_apple_hls").text("Apple HLS");
                $("#label_jpeg_url").text("JPEG URL");


            } else if(sourceElement[3].selected) {

                appleHls.removeClass('d-none')
                jpegURL.addClass('d-none')
                latitude.addClass('d-none')
                longitude.addClass('d-none')
                file.addClass('d-none')

                $('#id_apple_hls').attr('required', true);
                $('#id_jpeg_url').attr('required', false);
                $('#id_file').attr('required', false);

                $("#label_camera_name").text("Title");
                $("#label_apple_hls").text("Link");

            } else if (sourceElement[4].selected) {

                appleHls.addClass('d-none')
                jpegURL.addClass('d-none')
                latitude.addClass('d-none')
                longitude.addClass('d-none')
                file.removeClass('d-none')

                $('#id_apple_hls').attr('required', false);
                $('#id_jpeg_url').attr('required', false);
                $('#id_file').attr('required', true);

                $('#id_file').attr('accept', 'video/*');

                $("#label_camera_name").text("Video Title");
                $("#label_file").text("Video File");

            } else if (sourceElement[5].selected) {

                appleHls.addClass('d-none')
                jpegURL.addClass('d-none')
                latitude.addClass('d-none')
                longitude.addClass('d-none')
                file.removeClass('d-none')

                $('#id_apple_hls').attr('required', false);
                $('#id_jpeg_url').attr('required', false);
                $('#id_file').attr('required', true);

                $('#id_file').attr('accept', 'image/*');

                $("#label_camera_name").text("Image Title");
                 $("#label_file").text("Image File");

            }
        });
    });

</script>

apps/templates/modals/export_channel.html
<div class="modal fade" id="exportChannelModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true"
  >
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Export channel</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="" method="POST" class="pop-up-form__form" id="export_channel_form" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="mb-3" id="input-thumbnail">
                        <label for="export" class="form-label">Your items and all their data will be downloaded as a CSV file.</label>
                        <input type="hidden" id="export" name="export" value="true">
                    </div>

                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" form="export_channel_form" data-bs-dismiss="modal">Export</button>
            </div>
        </div>
    </div>
</div>

apps/templates/modals/image_resizer.html
<div class="modal fade" id="imageResizerModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true"
  >
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Image Resizer</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="" method="POST" class="pop-up-form__form" id="image_resizer_form" enctype="multipart/form-data">
                    {% csrf_token %}

                    <label for="id_resolution" class="col-form-label">Choose resolution</label>
                    <select class="form-select mb-3" name="resolution" id="id_resolution">
                        <option value="4k" selected>4k</option>
                        <option value="10x">10x</option>
                        <option value="Custom">Custom</option>
                    </select>

                    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center d-none" id="div-custom">
                        <div class="mb-3 col-6" style="padding-right:5px">
                            <label for="image_height" class="col-form-label">Height</label>
                            <input name="image_height" type="number" class="form-control" id="image_height" autocomplete="off"
                                   value="1920" min="0" max="10000" step="1"/>
                        </div>

                        <div class="mb-3 col-6"
                             style="padding-left:5px">
                            <label for="image_width" class="col-form-label">Width</label>
                            <input name="image_width" type="number" class="form-control" id="image_width" autocomplete="off"
                                   value="1080" min="0" max="10000" step="1"/>
                        </div>
                    </div>

                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" name="image_resizer_form" form="image_resizer_form" data-bs-dismiss="modal">Resize</button>
            </div>
        </div>
    </div>
</div>
<script>

    $(document).ready(function () {
        var resolution = $("select[name='resolution']");
        var cameraName = $('#div-custom');

        resolution.change(function(){
            var sourceElement = document.getElementById('id_resolution')

            if(sourceElement[2].selected) {
                cameraName.removeClass('d-none')
            } else {
                cameraName.addClass('d-none')
            }
        });
    });

</script>